import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { CTA } from "@/components/CTA";
import { PropertyCard } from "@/components/PropertyCard";
import { cities, properties, seoServices, slugify } from "@/lib/data";

export function generateStaticParams(){return seoServices.flatMap(s=>cities.map(c=>({service:s.slug,city:slugify(c)})));}
function getData(serviceSlug:string,citySlug:string){const service=seoServices.find(s=>s.slug===serviceSlug);const city=cities.find(c=>slugify(c)===citySlug);return {service,city};}
export async function generateMetadata({params}:{params:Promise<{service:string;city:string}>}):Promise<Metadata>{const p=await params;const {service,city}=getData(p.service,p.city);if(!service||!city)return{};return{title:`${service.label} a ${city}`,description:`${service.label} a ${city}: affidati a STARTHOME per una consulenza immobiliare locale, chiara e professionale.`};}
export default async function Page({params}:{params:Promise<{service:string;city:string}>}){const p=await params;const {service,city}=getData(p.service,p.city);if(!service||!city)notFound();const local=properties.filter(x=>x.city===city).slice(0,3);const isSelling=service.slug==="vendere-casa"||service.slug==="valutazione-casa";return <><section className="bg-sand py-20"><div className="container-site"><p className="eyebrow">{service.intro}</p><h1 className="display-title">{service.label}<br/><span className="italic text-gold">a {city}</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-ink/60">STARTHOME affianca proprietari, acquirenti e inquilini a {city} con conoscenza locale, comunicazione curata e un metodo costruito su obiettivi reali: prezzo, tempi, sicurezza e qualità dei contatti.</p><div className="mt-8 flex flex-wrap gap-3"><Link href={isSelling ? "/valutazione" : "/contatti"} className="btn-dark">{isSelling ? "Richiedi valutazione gratuita" : "Parla con un consulente immobiliare"}</Link><Link href="/vendere-casa" className="btn-outline">Metodo vendita STARTHOME</Link></div></div></section><section className="py-20"><div className="container-site grid gap-12 lg:grid-cols-[1fr_.8fr]"><div><h2 className="section-title">Esperienza sul territorio,<br/>strategia su misura.</h2><p className="mt-6 leading-8 text-ink/60">Conoscere {city} significa leggere differenze tra quartieri, servizi, collegamenti e tipologie più richieste. È da questa lettura puntuale che nasce una valutazione attendibile e una trattativa ben condotta.</p><p className="mt-5 leading-8 text-ink/60">Dalla prima consulenza fino alla firma, hai un referente presente, informazioni chiare e una gestione attenta di documenti, visite, negoziazione e prossimi passi.</p></div><div className="bg-ink p-9 text-white"><p className="eyebrow">Perché STARTHOME</p><ul className="space-y-5 text-sm leading-7 text-white/70"><li>Valutazioni basate su dati e conoscenza locale</li><li>Presentazione premium dell’immobile</li><li>Contatti selezionati e visite più qualificate</li><li>Assistenza tecnica e documentale</li><li>Aggiornamenti chiari, senza lasciare dubbi sospesi</li></ul></div></div></section>{local.length>0&&<section className="bg-mist py-20"><div className="container-site"><h2 className="section-title mb-10">Opportunità a {city}</h2><div className="grid gap-7 md:grid-cols-3">{local.map(x=><PropertyCard key={x.id} property={x}/>)}</div></div></section>}<CTA title={`Hai un immobile a ${city}?`} text="Richiedi una valutazione gratuita e scopri come posizionarlo correttamente sul mercato con una strategia chiara." href="/valutazione"/></>;}
