import type { Metadata } from "next";
import { CTA } from "@/components/CTA";

export const metadata: Metadata = { title: "Servizi immobiliari", description: "Vendita, locazione, valutazione, accesso a consulenza mutui tramite partner esterni e arredo casa su misura con artigiani locali." };
const items = [
  ["Vendere casa con strategia","Valutazione, posizionamento, presentazione premium, promozione mirata, selezione acquirenti e trattativa guidata fino al rogito."],
  ["Valutazione immobiliare","Una stima motivata da comparabili, domanda reale, microzona e caratteristiche dell’immobile. Il prezzo deve convincere il mercato, non solo il proprietario."],
  ["Marketing immobiliare premium","Foto, descrizioni, portali, database clienti, social e materiali di vendita pensati per generare contatti qualificati e visite migliori."],
  ["Affittare con tutela","Analisi del canone, presentazione, verifica affidabilità, contratto e gestione degli adempimenti per ridurre rischi e perdite di tempo."],
  ["Comprare con una guida","Ricerca, visite organizzate, lettura dei documenti, negoziazione e coordinamento tecnico-finanziario: una casa si sceglie con emozione, ma si compra con metodo."],
  ["Consulenza documentale","Controlli catastali e urbanistici con professionisti qualificati, per arrivare preparati alla proposta, al preliminare e alla firma."],
  ["Mutui tramite partner esterni","Ti mettiamo in contatto con consulenti del credito e intermediari abilitati esterni, per valutare sostenibilità e soluzioni di finanziamento coerenti."],
  ["Arredo casa su misura","Dalla cucina agli ambienti completi, selezioniamo artigiani locali e professionisti del territorio per soluzioni personalizzate e curate."],
];
export default function Page(){ return <><section className="bg-sand py-20"><div className="container-site"><p className="eyebrow">Competenza in ogni passaggio</p><h1 className="display-title">Servizi immobiliari<br/>con una regia precisa.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-ink/60">Non ti lasciamo con una lista di cose da fare. Ti accompagniamo con un metodo chiaro, professionisti selezionati e un referente che tiene insieme valutazione, marketing, trattativa e passaggi tecnici.</p><div className="mt-8 flex flex-wrap gap-3"><a className="btn-dark" href="/vendere-casa">Voglio vendere casa</a><a className="btn-outline" href="/valutazione">Richiedi valutazione gratuita</a></div></div></section><section className="py-20"><div className="container-site grid gap-px bg-ink/10 md:grid-cols-2 lg:grid-cols-4">{items.map(([t,d],i)=><article key={t} className="bg-white p-8 sm:p-10"><span className="font-serif text-5xl text-gold/35">{String(i+1).padStart(2,"0")}</span><h2 className="mt-8 font-serif text-3xl font-semibold">{t}</h2><p className="mt-4 text-sm leading-7 text-ink/60">{d}</p></article>)}</div><p className="container-site mt-8 text-xs leading-6 text-ink/45">I servizi finanziari sono erogati esclusivamente da soggetti esterni abilitati. STARTHOME REAL ESTATE facilita il contatto e non svolge attività di mediazione creditizia.</p></section><CTA title="Vuoi capire qual è la strada migliore?" text="Raccontaci il tuo obiettivo: vendita, acquisto, affitto o valorizzazione. Ti risponderemo con un primo orientamento concreto." button="Parla con un consulente immobiliare" href="/contatti"/></>; }
